# pubspec.yaml
# Amaç: Projenin bağımlılıklarını, varlıklarını ve yapılandırmalarını tanımlar.
# Konum: Proje kök dizini (nubar/)
# Bağlantı: Flutter, bu dosyayı paketleri ve varlıkları yönetmek için kullanır.

name: nubar
description: Kürt kültürünü korumak, yaşatmak ve dünya çapında tanıtmak amacıyla geliştirilen mobil uygulama.

# Uygulama versiyonu
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase paketleri - Backend hizmetleri için
  firebase_core: ^3.0.0          # Firebase temel paket
  firebase_auth: ^5.0.0          # Kimlik doğrulama için
  cloud_firestore: ^5.0.0        # Veritabanı için
  firebase_storage: ^12.0.0      # Medya depolama için
  firebase_analytics: ^11.0.0    # Kullanım analizi için
  firebase_dynamic_links: ^6.0.5 # Derin bağlantılar için (güncellendi)

  # Google ile giriş
  google_sign_in: ^6.2.1         # Google Sign-In için

  # Durum yönetimi

  # Görsel ve UI paketleri
  cupertino_icons: ^1.0.8        # iOS stil ikonlar
  cached_network_image: ^3.3.1   # Önbellekli görsel yükleme
  flutter_svg: ^2.0.10           # SVG dosyaları için
  shimmer: ^3.0.0                # Yükleme animasyonları

  # Yerelleştirme ve çoklu dil
  intl: ^0.19.0                  # Dil ve format desteği

  # Medya işleme
  image_picker: ^1.1.2           # Kamera/galeri erişimi
  video_player: ^2.9.1           # Video oynatma
  chewie: ^1.7.1                 # Video kontrolleri

  # Sosyal medya paylaşımı
  share_plus: ^9.0.0             # İçerik paylaşımı
  url_launcher: ^6.3.0           # Bağlantı açma

  # Çevrimdışı depolama ve önbellekleme
  shared_preferences: ^2.2.3     # Yerel depolama
  sqflite: ^2.3.3                # SQL veritabanı
  path_provider: ^2.1.3          # Dosya sistemi erişimi

  # Form ve validasyon
  form_field_validator: ^1.1.0   # Form validasyonu

  # JavaScript interop (web desteği için)
  js: ^0.6.7                     # Firebase web bağımlılıkları için

  # Diğer
  timeago: ^3.6.1                # Zaman formatlaması
  connectivity_plus: ^6.0.3       # İnternet bağlantısı kontrolü
  flutter_native_splash: ^2.4.1  # Açılış ekranı
  package_info_plus: ^8.0.0      # Uygulama bilgileri
  provider: 6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0          # Kod kalitesi kuralları

# Flutter yapılandırması
flutter:
  uses-material-design: true

  assets:
    - assets/images/           # Resimler
    - assets/icons/            # İkonlar
    - assets/animations/       # Animasyonlar

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic

  generate: true