name: nubar
description: >-
  Kürt kültürünü korumak, yaşatmak ve dünya çapında tanıtmak amacıyla
  geliştirilen mobil uygulama.

# Proje sürümü (versionName+versionCode)
version: 1.0.0+1

# ──────────────────────────────────────────────────────────────────────────────
# 1) Ortam (Dart SDK) sürüm kısıtlaması
environment:
  sdk: ">=3.0.0 <4.0.0"

# ──────────────────────────────────────────────────────────────────────────────
# 2) Ana bağımlılıklar
dependencies:
  flutter:
    sdk: flutter

  # Çoklu dil desteği (yerelleştirme)
  flutter_localizations:
    sdk: flutter

  # Tarih/saat, sayılar vb. için uluslararasılaştırma
  intl: ^0.19.0

  # Firebase çekirdek modülü ve servisler
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  firebase_analytics: ^10.4.4
  firebase_dynamic_links: ^5.3.4

  # Google ile giriş
  google_sign_in: ^6.3.0

  # Durum yönetimi (MVVM için)
  provider: ^6.0.5

  # UI ve yardımcı paketler
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0

  # Medya işlemleri
  image_picker: ^1.0.1
  video_player: ^2.7.0
  chewie: ^1.7.0
  share_plus: ^7.1.0
  url_launcher: ^6.1.12

  # Yerel depolama ve veri tabanı
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  connectivity_plus: ^4.0.2

  # Form validasyonu ve yardımcı paketler
  form_field_validator: ^1.1.0
  timeago: ^3.5.0
  package_info_plus: ^4.1.0

  # Splash ekran yönetimi
  flutter_native_splash: ^2.3.1

# ──────────────────────────────────────────────────────────────────────────────
# 3) Geliştirme bağımlılıkları
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

# ──────────────────────────────────────────────────────────────────────────────
# 4) Flutter özel ayarları
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic

# ──────────────────────────────────────────────────────────────────────────────
# 5) Flutter Intl Yapılandırması
flutter_intl:
  enabled: true
  main_locale: ku
  arb_dir: lib/l10n
  output_dir: lib/generated
  class_name: S
  template_arb_file: app_en.arb  # Varsayılan template dosyasını açıkça belirtiyoruz
  output_localization_file: l10n.dart