# pubspec.yaml
# Amaç: Projenin bağımlılıklarını, varlıklarını ve yapılandırmalarını tanımlar.
# Konum: Proje kök dizini (nubar/)
# Bağlantı: Flutter, bu dosyayı paketleri ve varlıkları yönetmek için kullanır.

name: nubar
description: >-
  Kürt kültürünü korumak, yaşatmak ve dünya çapında tanıtmak amacıyla
  geliştirilen mobil uygulama.

# Proje sürümü (versionName+versionCode)
version: 1.0.0+1

# Ortam (Dart SDK) sürüm kısıtlaması
environment:
  sdk: ">=3.0.0 <4.0.0"

# Ana bağımlılıklar
dependencies:
  flutter:
    sdk: flutter

  # Çoklu dil desteği (yerelleştirme)
  flutter_localizations:
    sdk: flutter

  # Tarih/saat, sayılar vb. için uluslararasılaştırma
  intl: ^0.19.0

  # Firebase çekirdek modülü ve servisler
  firebase_core: ^3.6.0  # Güncellendi
  firebase_auth: ^5.3.1  # Güncellendi
  cloud_firestore: ^5.4.4  # Güncellendi
  firebase_storage: ^12.3.2  # Güncellendi
  firebase_analytics: ^11.3.3  # Güncellendi
  firebase_dynamic_links: ^6.0.5  # Güncellendi

  # Google ile giriş
  google_sign_in: ^6.3.0

  # Durum yönetimi (MVVM için)
  provider: ^6.1.2  # Güncellendi

  # UI ve yardımcı paketler
  cupertino_icons: ^1.0.8  # Güncellendi
  cached_network_image: ^3.3.1  # Güncellendi
  flutter_svg: ^2.0.10  # Güncellendi
  shimmer: ^3.0.0

  # Medya işlemleri
  image_picker: ^1.1.2  # Güncellendi
  video_player: ^2.9.2  # Güncellendi
  chewie: ^1.8.3  # Güncellendi
  share_plus: ^10.0.3  # Güncellendi
  url_launcher: ^6.3.1  # Güncellendi

  # Yerel depolama ve veri tabanı
  shared_preferences: ^2.3.2  # Güncellendi
  sqflite: ^2.3.3  # Güncellendi
  path_provider: ^2.1.4  # Güncellendi
  connectivity_plus: ^6.0.5  # Güncellendi

  # Form validasyonu ve yardımcı paketler
  form_field_validator: ^1.1.0
  timeago: ^3.7.0  # Güncellendi
  package_info_plus: ^8.0.2  # Güncellendi

  # Splash ekran yönetimi
  flutter_native_splash: ^2.4.1  # Güncellendi

# Geliştirme bağımlılıkları
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Güncellendi

# Flutter özel ayarları
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic

# Flutter Intl Yapılandırması
flutter_intl:
  enabled: true
  main_locale: ku
  arb_dir: lib/l10n
  output_dir: lib/generated
  class_name: S
  template_arb_file: app_en.arb
  output_localization_file: l10n.dart