# pubspec.yaml
# Amaç: Projenin bağımlılıklarını, varlıklarını ve yapılandırmalarını tanımlar.
# Konum: Proje kök dizini (nubar/)
# Bağlantı: Flutter, bu dosyayı paketleri ve varlıkları yönetmek için kullanır.

name: nubar
description: Kürt kültürünü korumak, yaşatmak ve dünya çapında tanıtmak amacıyla geliştirilen mobil uygulama.

# Uygulama versiyonu
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase paketleri - Backend hizmetleri için
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_analytics: ^11.0.0
  # firebase_dynamic_links kaldırıldı çünkü kullanımdan kalkmış

  # Google ile giriş
  google_sign_in: ^6.2.1

  # Durum yönetimi
  provider: ^6.0.5

  # Görsel ve UI paketleri
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0

  # Yerelleştirme ve çoklu dil
  intl: ^0.19.0

  # Medya işleme
  image_picker: ^1.1.2
  video_player: ^2.9.1
  chewie: ^1.7.1

  # Sosyal medya paylaşımı
  share_plus: ^9.0.0
  url_launcher: ^6.3.0

  # Çevrimdışı depolama ve önbellekleme
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path_provider: ^2.1.3

  # Form ve validasyon
  form_field_validator: ^1.1.0

  # Diğer
  timeago: ^3.6.1
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.4.1
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter yapılandırması
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic

  generate: true