// File generated by Firebase CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Bu bilgiler Firebase konsolundan gelmelidir. Şu an örnek değerler içeriyor.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'nubar-web-api-key',
    appId: 'nubar-web-app-id',
    messagingSenderId: 'nubar-messaging-sender-id',
    projectId: 'nubar-project-id',
    authDomain: 'nubar-auth-domain',
    storageBucket: 'nubar-storage-bucket',
    measurementId: 'nubar-measurement-id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'nubar-android-api-key',
    appId: 'nubar-android-app-id',
    messagingSenderId: 'nubar-messaging-sender-id',
    projectId: 'nubar-project-id',
    storageBucket: 'nubar-storage-bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'nubar-ios-api-key',
    appId: 'nubar-ios-app-id',
    messagingSenderId: 'nubar-messaging-sender-id',
    projectId: 'nubar-project-id',
    storageBucket: 'nubar-storage-bucket',
    iosClientId: 'nubar-ios-client-id',
    iosBundleId: 'nubar-ios-bundle-id',
  );
}