// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkVflISQFbPLHInJofXzH9i_vqs6L4q80',
    appId: '1:946251429774:web:056e215f5328b2372116df',
    messagingSenderId: '946251429774',
    projectId: 'deneme-12355',
    authDomain: 'deneme-12355.firebaseapp.com',
    storageBucket: 'deneme-12355.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV9_7HEbNmp1Vs2yw7KkzkFk_3ty2PmhI',
    appId: '1:946251429774:android:f5fd944099753ccd2116df',
    messagingSenderId: '946251429774',
    projectId: 'deneme-12355',
    storageBucket: 'deneme-12355.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtpQLt4IHc5EgUuFm_hLKBRK9POsvjcQc',
    appId: '1:946251429774:ios:f69c2df30a94d1ee2116df',
    messagingSenderId: '946251429774',
    projectId: 'deneme-12355',
    storageBucket: 'deneme-12355.firebasestorage.app',
    iosBundleId: 'com.example.nubar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtpQLt4IHc5EgUuFm_hLKBRK9POsvjcQc',
    appId: '1:946251429774:ios:f69c2df30a94d1ee2116df',
    messagingSenderId: '946251429774',
    projectId: 'deneme-12355',
    storageBucket: 'deneme-12355.firebasestorage.app',
    iosBundleId: 'com.example.nubar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkVflISQFbPLHInJofXzH9i_vqs6L4q80',
    appId: '1:946251429774:web:73aeb727cc354a122116df',
    messagingSenderId: '946251429774',
    projectId: 'deneme-12355',
    authDomain: 'deneme-12355.firebaseapp.com',
    storageBucket: 'deneme-12355.firebasestorage.app',
  );
}
